name: Build binaries

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: "Enter msvc build environment"
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
    - name: Build project
      shell: cmd
      run: |
        qmake
        nmake
    - name: Package output
      run: |
        mkdir dist
        mkdir dist/SoETilesViewer
        dir release
        cp release/SoETilesViewer.exe dist/SoETilesViewer/
        cp LICENSE dist/SoETilesViewer/
        cd dist/SoETilesViewer
        windeployqt SoETilesViewer.exe
        dir
        cd ..
        Compress-Archive -Path SoETilesViewer -DestinationPath ../SoETilesViewer-win64.zip
    - name: Store output
      uses: actions/upload-artifact@v4
      with:
        name: SoETilesViewer-win64
        path: SoETilesViewer-win64.zip

